### ISSUE TITLE
Can we disable this package ? 

### ISSUE THREAD

**Issue by onuralpszr** [muchpack/openh264#1]
Hello; Fedora has added this package in main repository and maintain by "cisco" itself. When It can enable just with a single line. So could be leave to main people who maintain it. ? 

UnitedRPM version : openh264-1.5.0-1.20160419git2610ab1.fc24
Fedora version : openh264-1.5.2-0.4.git21e44bd.fc24

Additional info:  https://fedoraproject.org/wiki/OpenH264

Thank you.

**Comment by paulcarroty** [comment]
Hi @thunderbirdtr, of course, but we need to test first

```
# repoquery --whatrequires openh264 --source | perl -pe 's/-\d.*?-\d+(\..*)?\.fc\d+(\..*)?.src.rpm//' | sort -u

gstreamer1-plugins-bad-freeworld
```

with new version of library.

**Comment by paulcarroty** [comment]
@thunderbirdtr openh264 is now available in F24 repository? Copr can't find it.

**Comment by onuralpszr** [comment]
Not copr ? It's in here; When we install It's coming default but not enabled we just need to enable and next release gonna be default too and enabled.

https://codecs.fedoraproject.org/openh264/

**Comment by paulcarroty** [comment]
@sergiomb2 @kuboosoft what you think about it?

I personally think that we can distribute this package here until this repo will be enable by default. 

P.S. Openh264 from Cisco supports only h264 baseline profile.

**Comment by sergiomb2** [comment]
we have another report  https://github.com/UnitedRPMs/gstreamer1-plugins-bad-freeworld/issues/1

**Comment by sergiomb2** [comment]
Hum ,  https://fedoraproject.org/wiki/OpenH264 says: does not enable generic H.264 playback, only WebRTC (see Mozilla bug 1057646).

**Comment by paulcarroty** [comment]
>  does not enable generic H.264 

Nice, no sense to use and support it. `gstreamer1-plugins-bad-freeworld` was rebuilded without openh264.

**Comment by kuboosoft** [comment]
I recommend only add a "Provides: foo =version-release " to our gstreamer... and delete (openh264) when it is ready in Fedora 25... because we will cut a capability; without a package not provided by default in Fedora...

**Comment by paulcarroty** [comment]
Deleted.

**Comment by kuboosoft** [comment]
Isn't a simple delete @paulcarroty I made now the changes, we can't delete capabilities, for a issue with [large legal process](https://fedoraproject.org/wiki/Non-distributable-rpms).  I don't see people from 'fedora-cisco-openh264' help to unitedrpms; sorry but the project is serious project.
